# Rendered at deploy-time via envsubst with GH Actions secrets in scope.
KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD
DATABASE_URL=$PRODUCTION_DATABASE_URL
POSTGRES_PASSWORD=$PRODUCTION_POSTGRES_PASSWORD
REDIS_URL=$PRODUCTION_REDIS_URL
